server:
  port: 8080    # TODO: 모듈별 포트번호 다르게 지정 필요

spring:
  profiles:
    active: local   #기본은 local (test 작성시에는 어플리케이션에 test 명시, prod 경우 docker 컨테이너 띄울 때(jar 파일 명령) profile 작성
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: # database url
    username: # database username
    password: # database password
  jpa:
    open-in-view: false

logging:
  level:
    root: INFO      # FIXME: 로그 전략 수립 필요(현재는 전부 다 허용) => 패키지별로 하던지 등 ...
  charset:
    console: UTF-8
