#컨테이너로 띄울 서비스들 정의
services:
  mysql:
    image: mysql:latest  #공식 MySQL 도커 이미지를 최신 버전으로 사용
    container_name: pickcar_mysql_dev #컨테이너 이름
    restart: no #컨테이너가 죽거나 서버 재부팅 시 자동으로 재시작합니다.(TODO: 운영은 always 설정 필요)
    env_file:
      - ./.env.dev
    environment: #MySQL 환경변수를 지정하여 DB 초기 설정
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
      MYSQL_DATABASE: ${DB_NAME_DEV}
      MYSQL_USER: ${DB_USERNAME_DEV}
      MYSQL_PASSWORD: ${DB_PASSWORD_DEV}
    ports:
      - "3306:3306"
    networks:
      - backend_dev

  domain:
    build: # 이 서비스를 빌드할 때 사용할 설정
      context: .. #도커 빌드 컨텍스트가 현재 디렉토리의 상위 디렉토리임을 의미합니다. (즉, 루트 폴더 기준으로 빌드)
      dockerfile: domain/Dockerfile.dev #도커파일 경로 지정 (루트/domain/Dockerfile)
    container_name: pickcar_domain_dev
    restart: no #(TODO: 운영은 always로 설정 필요)
    env_file:
      - ./.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev # spring boot에서 활성화할 profile = dev
      DEV_DB_NAME: ${DB_NAME_DEV}
      DEV_DB_USERNAME: ${DB_USERNAME_DEV}
      DEV_DB_PASSWORD: ${DB_PASSWORD_DEV}
    depends_on: #domain 컨테이너보다 먼저 시작되어야할 것들 명시 (의존하고 있는 것 명시)
      - mysql
    ports: #호스트 8080포트를 컨테이너 8080포트로 연결
      - "8080:8080"  # 외부:내부 포트
    networks:
      - backend_dev

# ex)
#  emulator:
#    build:
#      context: ..
#      dockerfile: emulator/Dockerfile.dev
#    container_name: pickcar_emulater_dev
#    restart: no #TODO: 운영은 always로 설정 필요
#    environment: #필요한 환경변수
#      SPRING_PROFILES_ACTIVE: dev #TODO: 운영은 prod로 설정 필요
#      DEV_DB_NAME: ${DB_NAME_DEV}
#      DEV_DB_USERNAME: ${DB_USERNAME_DEV}
#      DEV_DB_PASSWORD: ${DB_PASSWORD_DEV}
#    depends_on: #emulator 컨테이너보다 먼저 시작되어야할 것들 명시 (의존하고 있는 것 명시)
#      - mysql
#    ports: 
#      - "8081:8080"  #TODO: 팀 회의를 통해 지정 필요
#    networks:
#      - backend_dev

#컨테이너 간 통신을 위한 네트워크 정의
networks:
  backend_dev: