name: Deploy to EC2 on dev branch push

#dev branch로 push하면 실행
on:
  push:
    branches:
      - dev

#배포 작업 정의
jobs:
  #ubuntu VM에서 실행
  deploy:
    runs-on: ubuntu-latest

    steps:
      #워크플로우 VM(GitHub Actions 가상 머신)에 현재 레포지토리 코드를 내려받기
      - name: Checkout code
        uses: actions/checkout@v4

      #EC2에 접속할 SSH 개인키를 GitHub Actions에 등록해 SSH 접속 준비
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_ACTIONS_KEY }}

      #gradlew 스크립트에 실행 권한을 줘서 Gradle 빌드 가능하도록 설정
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      #테스트 제외하고 프로젝트 빌드 (jar 등 생성)
      - name: Build with Gradle
        run: ./gradlew clean build -x test #TODO: 테스트 수행 시 수정 필요 (-x test 제거)

      #rsync로 워크플로우 VM에서 EC2의 특정 디렉토리로 코드 복사하기 (단, .git, .github 제외) (TODO : 민감한 파일/폴더는 --exclude로 설정)
      - name: Copy project source code to EC2 (excluding .git, .github)
        run: |
          rsync -avz --delete --exclude='.git' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/pickcar_dev

      #EC2에 직접 SSH로 접속해 .env 파일 생성 (비밀정보 환경변수 세팅)
      - name: Create .env file on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_ACTIONS_KEY }}
          script: |
            set -e
            cd /home/ubuntu/pickcar_dev/docker
            cat > .env.dev <<EOL
            MYSQL_ROOT_PASSWORD_DEV=${{ secrets.MYSQL_ROOT_PASSWORD_DEV }}
            DB_NAME_DEV=${{ secrets.DB_NAME_DEV }}
            DB_USERNAME_DEV=${{ secrets.DB_USERNAME_DEV }}
            DB_PASSWORD_DEV=${{ secrets.DB_PASSWORD_DEV }}
            EOL
            echo "docker/.env.dev created successfully"

      #EC2에서 application-dev.yml 파일 생성
      - name: Create application-dev.yml on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_ACTIONS_KEY }}
          script: |
            set -e
            cd /home/ubuntu/pickcar_dev/domain/src/main/resources
            rm -f application-dev.yml
            cp application-dev.default application-dev.yml
            echo "application-dev.yml created successfully"

      #EC2에서 기존 docker-compose container 중지 및 정리 -> 도커 이미지 빌드(캐시 무시) -> 컨테이너 재실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_ACTIONS_KEY }}
          script: |
            set -e
            cd /home/ubuntu/pickcar_dev
            sudo docker compose --env-file docker/.env.dev -f docker/docker-compose.dev.yml down
            sudo docker container prune -f
            sudo docker compose --env-file docker/.env.dev -f docker/docker-compose.dev.yml build --no-cache
            sudo docker compose --env-file docker/.env.dev -f docker/docker-compose.dev.yml up -d
            echo "Docker container is up and running"